image: node

stages:
 # I just want to lint, so I will create a "lint" stage
 - lint

# Lets name our Job eslint, because that's what it's doing.
eslint:
 # tell eslint what stage it is. (This could also be build or test for example)
 stage: lint
 # What scripts do we want to run?
 script:
    # install eslint
    # - npm install
    - npm --proxy http://jurosutantra:41455108@cache.itb.ac.id:8080 install
    - node_modules\.bin\eslint *.js --fix
    # - node_modules\.bin\eslint *.jsx --fix
